import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    baseUrl: "http://localhost:5173", // URL del front
    video: true,
    screenshotOnRunFailure: true,
    setupNodeEvents(on, config) {
      // Configuración adicional o hooks
    },
    env: {
      backendUrl: "http://localhost:3000",
      authUrl: "http://localhost:3001",
    },
  },
});
