version: '3.8'

services:
  frontend:
    image: ghcr.io/ics-pa-2025/2025_proyecto2_front_safestore:latest
    container_name: 2025_proyecto2_front_safestore
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - microservices

networks:
  microservices:
    name: safestore-microservices
    external: false
