version: '3.8'

services:
  frontend:
    image: ghcr.io/ics-pa-2025/2025_proyecto2_front_safestore:latest
    container_name: safestore-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
