name: CI/CD - Build & Deploy (frontend)

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/ics-pa-2025/2025_proyecto2_front_safestore:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_AUTH_API_URL=${{ secrets.VITE_AUTH_API_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Wait for image propagation
        run: sleep 10

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.DROPLET_SSH_PORT || '22' }}
          script: |
            set -e
            mkdir -p /home/${{ secrets.DROPLET_USER }}/2025_proyecto2_front_safestore
            cd /home/${{ secrets.DROPLET_USER }}/2025_proyecto2_front_safestore
            # Download the docker-compose.prod.yml if it doesn't exist
            if [ ! -f docker-compose.prod.yml ]; then
              curl -o docker-compose.prod.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.prod.yml
            fi
            docker pull ghcr.io/${{ github.repository_owner }}/2025_proyecto2_front_safestore:latest
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
